---
title: "Project Proposal"
author: 
    - Vismayie Vandanapu
    - Ankit Kumar
    - Martin Arienmughare
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Project Title
Obvious and hidden gamma in credit derivative land

## Names of all group members
Vismayie Vandanapu \newline Ankit Kumar \newline Martin Arienmughare

## Name and contact information for your mentor
Leon Tatevossian (lt56@nyu.edu)

## A two or three sentence statement of the problem


## A two or three sentence statement of the approach you intend to take



## A two or three sentence statement of your criteria of success





\newpage

# References

1. Correlation Risk Management and Modeling: An applied guide including the Basel III correlation framework with interactive correlation models in Excel/VBA.  *Gunter Meissner*. [John Wiley & Sons, 2014]. (Chapters 1, 4 & 5)

2. Options, Futures and Other Derivatives.  *John Hull*. [Pearson, 10th Edition]. (Chapters 7, 9, 19, 22, 24, 25, 34)

3. [A New Approach For Modelling and Pricing Correlation Swaps](http://quantlabs.net/academy/download/free_quant_instituitional_books_/[Dresdner%20Kleinwort]%20A%20New%20Approach%20For%20Modeling%20and%20Pricing%20Correlation%20Swaps.pdf). *Sebastien Bossu*. [Dresdner Kleinwort, version of May 2007].

4. [Valuation and Hedging of Correlation Swaps](https://pdfs.semanticscholar.org/c6f5/27405b2d10d7dc44a8b82714695038948474.pdf?_ga=2.220275800.1161641639.1571824983-328890972.1571824983). *Mats Draijer*. [September 2017 version]. 

5. [Pricing Credit Default Swap Subject to Counterparty Risk and Collateralization](https://arxiv.org/pdf/1803.07843.pdf). *Alan White*. [FinPricing].

6. [CCP Cleared or Bilateral CSA Trades with Initial/Variation Margins under credit, funding and wrong\-way risks: A Unified Approach](https://arxiv.org/pdf/1401.3994.pdf). [arXiv:401.3994v1].

7. [Pricing credit default swaps with bilateral value adjustments](https://arxiv.org/pdf/1207.6049.pdf). *Alexander Lipton, Ioana Savescu*. [arXiv:1207.6049v1].

8. [A structural approach to pricing credit default swaps with credit and debt value adjustments](https://arxiv.org/pdf/1206.3104.pdf). *Alexander Lipton, Ioana Savescu*. [arXiv:1206.3104v1].

9. [A CB (corporate bond) pricing probabilities and recovery rates model for deriving default probabilities and recovery rates](https://arxiv.org/pdf/1206.4766.pdf). *Takeaki Kariya*. [arXiv:1206.4766v2].

10. [Correlation breakdown, copula credit default models and arbitrage](https://arxiv.org/pdf/0908.4299.pdf). *Rodanthy Tzani*. [arXiv:0908.4299v1].

11. [One math geek's plan to reform Wall Street](https://www.newsweek.com/one-math-geeks-plan-reform-wall-street-80135). *Matthew Philips*. [Newsweek, May 5, 2009 8PM EDT ]

12. [Counterparty Risk and Counterparty Choice in the Credit Default Swap Market](http://w4.stern.nyu.edu/finance/docs/pdfs/Seminars/1803/1803w-du.pdf). *Wenxin Du Salil, Gadgil, Michael B. Gordy, Clara Vega*. []

13. [Variance Dispersion and Correlation Swaps](https://arxiv.org/pdf/1004.0125.pdf). *A. Jacquier, S. Slaoui*. [arXiv:1004.0125v1].

14. [Constant Maturity Credit Default Swap Pricing with Market Models](https://arxiv.org/pdf/0812.4159.pdf). *Damiano Brigo*. [arXiv:0812.4159v1].

15. [Bilateral counterparty risk valuation with stochastic dynamical models
and application to Credit Default Swaps
](https://arxiv.org/pdf/0812.3705.pdf). *Damiano Brigo*. [arXiv:0812.3705v4]

16. [Valuation of Credit Default Swap with Counterparty Default Risk by Structural Model](https://www.scirp.org/pdf/AM20100100022_82848886.pdf). *Jin Liang*, *Peng Zhou*, *Yujing Zhou*, *Junmei Ma*. [Applied Mathematics, 2011, 2, 106-117]

17. [Counterparty Credit Risk in OTC Derivatives under Basel III](https://www.scirp.org/pdf/JMF_2016123016343974.pdf). *Mabelle Sayah*. [Journal of Mathematical Finance, 2017, 7, 1-38]

18. [Pricing of Swapswith Default Risk](https://link.springer.com/content/pdf/10.1007%2FBF01531336.pdf). *Haitao Li*. [Review of Derivatives Research, 2, 231-250(1998)].

19. [An Empirical Comparison of Credit Spreads between the Bond Market and the Credit Default Swap Market](https://link.springer.com/content/pdf/10.1007%2Fs10693-006-7626-x.pdf). *Haibin Zhu*. [J Finan Serv Res (2006) 29: 211–235]

20. [Credit Risk Management for Derivatives](https://link.springer.com/content/pdf/10.1007%2F978-3-319-57975-7_2.pdf). *I. Zelenko*. [DOI 10.1007/978-3-319-57975-7_2]. (Chapter: Outlining Counterparty Credit Risk Exposure)

21. [The Credit Spread Puzzle](https://ssrn.com/abstract=1968448). *Jeffery D Amato, Eli M Remolona*. [BIS Quarterly Review, December 2003]

22. [A value at risk analysis of credit default swaps](https://www.econstor.eu/bitstream/10419/19789/1/200812dkp_b_.pdf). *Burkhard Raunig, Martin Scheicher*. []

23. [Wrong-way-risk in tails](https://link.springer.com/article/10.1057/s41260-018-0076-9). *Janis Muller, Peter N. Posch*. [J Asset Manag (2018) 19: 205]

<!-- x. [](). **. [] -->

<!-- x. [](). **. [] -->

<!-- x. [](). **. [] -->





